# Generated by Django 5.1.7 on 2025-03-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alumniprofile_bio_alumniprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
